lugorguk/lug.org.uk-website

admins.md
=> Tidied up admins page

admins.md
Change server for my GPG key lookup and add an email address for Gavin (me).
=> Change GPG Server for lookup & add email address

_posts/0000-01-01-Isle of Wight.md
Update Lugmaster's email address as per emailed request.
=> Update 0000-01-01-Isle of Wight.md

_sass/blog/_layout.scss, index.md
This should improve the experience on a mobile device.
=> Allow map to resize responsively

_posts/0000-01-01-Bristol and Bath.md
Updated contacts details to reflect current lugmaster/lug contact of the Bristol & Bath LUG.
=> Updated details of Bristol & Bath LUG

admins.md
=> Fix links to PGP Keyservers

_posts/0000-01-01-Cambridge.md
Tom asked us to change the mail address in 2018-05-15. As the ML is also 404'ing, I've removed this link too - which resolves #37
=> Cambridge LUG fixes

_posts/0000-01-01-Wolverhampton.md
=> Updated the mailman URL for wolveslug

_posts/0000-01-01-Ayrshire.md
Add LUG details for the newly reborn Ayrshire LUG.
=> Add Ayrshire LUG

_posts/0000-01-01-East Grinstead.md
Update East Grinstead (EG) LUG's details.
Fixes #53
=> Update 0000-01-01-East Grinstead.md

_posts/0000-01-01-Ayrshire.md
=> Removes S from HTTPS in Ayrshire LUG website

_posts/0000-01-01-Coventry.md
Further to #59 and the comments from @tadgy, this PR updates the entry accordingly.
=> Updates following #59

_posts/0000-01-01-Berkshire & Thames Valley Silicon Corridor.md
=> Update 0000-01-01-Berkshire & Thames Valley Silicon Corridor.md

_posts/0000-01-01-Somerset.md
Add Somerset LUG to the list of LUGs.
=> Add new Somerset LUG

_posts/0000-01-01-Portsmouth and South East Hampshire.md
Minor tweaks of URL, latitude and longitude and ensuring the last updated is current to show we are definitely still active.
=> Update 0000-01-01-Portsmouth and South East Hampshire.md

_layouts/default.html, lugs/East-Midlands.html, lugs/East.html, lugs/London.html, lugs/North-East.html, lugs/North-West.html, lugs/Northern-Ireland.html, lugs/Other.html, lugs/Scotland.html, lugs/South-East.html, lugs/South-West.html, lugs/Wales.html, lugs/West-Midlands.html, lugs/Yorkshire-and-Humber.html, lugs/index.html
=> Turn "Status" into a dropdown, filter records accordingly

_posts/0000-01-01-Berkshire & Thames Valley Silicon Corridor.md, _posts/0000-01-01-Birmingham.md, _posts/0000-01-01-Dorset.md, _posts/0000-01-01-Herefordshire.md, _posts/0000-01-01-Isle Of Man.md, _posts/0000-01-01-Isle of Wight.md, _posts/0000-01-01-Liverpool (LivLUG).md, _posts/0000-01-01-Milton Keynes.md, _posts/0000-01-01-Newark.md, _posts/0000-01-01-Sheffield.md, _posts/0000-01-01-Shropshire.md, _posts/0000-01-01-Staffordshire.md, _posts/0000-01-01-Teesside.md, _posts/0000-01-01-Tyneside (Newcastle).md, _posts/0000-01-01-Wolverhampton.md
Updating LUGs that are confirmed active and/or required changes.
closes https://github.com/lugorguk/lug.org.uk-website/issues/171
=> LUG status updates 2025

_posts/0000-01-01-Gloucestershire & Cotswolds.md, _posts/0000-01-01-Leicester.md, _posts/0000-01-01-Rugby.md, _posts/0000-01-01-Surrey.md
Update Gloucestershire & Cotswolds, Surrey, Leicester, and Rugby LUGs.
=> 2025 LUG Check-In and Updates (Part 2)

_layouts/default.html
=> Fix JavaScript for statusFilter present on individual LUG pages and homepage

_posts/0000-01-01-Lincolnshire.md, _posts/0000-01-01-Portsmouth and South East Hampshire.md, _posts/0000-01-01-Sheffield.md
Lincolnshire change closes #153
=> Lug status update 2025
